version = 0.1
[default.global.parameters]
stack_name = "gotcha-interface-alpha"
region = "us-east-2"
s3_bucket = "serverless-artifact"
s3_prefix = "gotcha-interface-alpha"

[dev.global.parameters]
stack_name = "gotcha-interface-alpha"
region = "us-east-2"
s3_bucket = "serverless-artifact"
s3_prefix = "gotcha-interface-alpha"
tags = "project=\"gotcha-interface\" environment=\"dev\""
parameter_overrides = "Environment=\"dev\""

[prd.global.parameters]
stack_name = "gotcha-interface-prd"
region = "us-east-2"
s3_bucket = "serverless-artifact"
s3_prefix = "gotcha-interface-prd"
tags = "project=\"gotcha-rest-prd\" environment=\"prd\""
parameter_overrides = "Environment=\"prd\""

[default.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "project=\"gotcha-interface\" environment=\"dev\""
parameter_overrides = "Environment=\"dev\""

[dev.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"

[prd.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
