AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless api with api gateway secured with IAM role, Cognito User Pool and Identity Pool
  Lambda is written in Java and Micronaut, and built in Graalvm.

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - uat
      - prd
    Description: Environment name

Mappings: 
  MemorySizeMap: 
    dev: 
      MemorySize: 256
    uat: 
      MemorySize: 256
    prod: 
      MemorySize: 512
  EnvironmentMap:
    dev:
      name: alpha
    uat:
      name: beta
    prd:
      name: prod 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    

Resources:
  GotchaApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./aws-template/api-gateway-template.yaml
      Parameters:
        EnvironmentName: !FindInMap [EnvironmentMap, !Ref Environment, 'name']
  CognitoResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./aws-template/cognito-cf-template.yaml
      Parameters:
        EnvironmentName: !FindInMap [EnvironmentMap, !Ref Environment, 'name']
        GotchaApiId: !GetAtt GotchaApi.Outputs.GotchaApiId
    DependsOn: GotchaApi        
