AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless api with api gateway secured with IAM role.
  Lambda is written in Java and Micronaut, and built in Graalvm.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod
    Description: Environment name

Mappings: 
  MemorySizeMap: 
    dev: 
      MemorySize: 256
    uat: 
      MemorySize: 256
    prod: 
      MemorySize: 512

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      Auth:
        DefaultAuthorizer: AWS_IAM

  GotchaRestLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Runtime: provided
      MemorySize: !FindInMap [MemorySizeMap, !Ref Environment, MemorySize]
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      PackageType: Zip
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      BuildMethod: makefile            

Outputs:
  GotchaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/'
    Export:
      Name: GotchaApi