FROM amazon/aws-sam-cli-build-image-java11

RUN yum install -y gcc gcc-c++ libc6-dev  zlib1g-dev curl bash zlib zlib-devel zip

ENV GRAAL_VERSION 22.0.0.2
ENV GRAAL_FILENAME graalvm-ce-java11-linux-amd64-${GRAAL_VERSION}.tar.gz
ENV GRAAL_FOLDERNAME graalvm-ce-java11-${GRAAL_VERSION}

RUN yum install -y wget \
	&& yum install -y tar \
	&& yum install -y gzip \
	&& wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${GRAAL_VERSION}/${GRAAL_FILENAME} \
	&& tar -xzvf ${GRAAL_FILENAME} \
  && ls \
	&& rm ${GRAAL_FILENAME} \
  && pwd \
	&& mv ${GRAAL_FOLDERNAME} /graalvm-ce-java11 \
  && ls /graalvm-ce-java11/bin

RUN export PATH="/graalvm-ce-java11/bin:$PATH" \
	&& gu install native-image \
	&& wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz \
	&& tar -xzvf apache-maven-3.3.9-bin.tar.gz \
	&& yum group install -y "Development Tools"

ENV PATH="/graalvm-ce-java11/bin:/apache-maven-3.3.9/bin:${PATH}"
ENV JAVA_HOME "/graalvm-ce-java11"